### ISSUE TITLE
[MacOS Mojave] Informed load causes the game to not launch under macos

### ISSUE THREAD

**Issue by ghost** [TeamAOF/AOF-Strawberry#12]
the issue revolves around the mod informed launch causes the game to stuck on load...

once disabled everything working fine.

a suggestion what to do:
we need probobly to inform the dev behind the mod about the issue and that he needs to fix or disable it for the meantime for the modpack at first launch.

a zip file is attached with those logs.
[THELOGFILESOFTHEISSUE.zip](https://github.com/AllOfFabric/AOF-Strawberry/files/3512024/THELOGFILESOFTHEISSUE.zip)

**Comment by calloatti** [comment]
BROKEN LAUNCH (WHEN INFORMED LOAD IS ENABLED): https://paste.ee/p/2UyBv
FIXED LAUNCH (LAUNCHES NORMALLY ONCE DISABLED INFORMED LOAD): https://paste.ee/p/GjllK
