### ISSUE TITLE
Ticking player error

### ISSUE THREAD

**Issue by FoxyLight** [TeamAOF/AOF-Strawberry#25]
Hi I seem to be getting a ticking player error that I can't seem to figure out. I've looked at several different solutions and no luck. Any ideas?

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7/31/20 9:55 AM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at net.minecraft.class_1657.handler$bek003$tick(class_1657.java:6288)
	at net.minecraft.class_1657.method_5773(class_1657.java:322)
	at net.minecraft.class_3222.method_14226(class_3222.java:421)
	at net.minecraft.class_3244.method_18784(class_3244.java:206)
	at net.minecraft.class_2535.method_10754(class_2535.java:233)
	at net.minecraft.class_3242.method_14357(class_3242.java:170)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:884)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$5723/1048288523.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1657.handler$bek003$tick(class_1657.java:6288)
	at net.minecraft.class_1657.method_5773(class_1657.java:322)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 216
	Entity Name: FoxyLight
	Entity's Exact location: -130.50, 66.00, 130.50
	Entity's Block location: World: (-131,66,130), Chunk: (at 13,4,2 in -9,8; contains blocks -144,0,128 to -129,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:421)
	at net.minecraft.class_3244.method_18784(class_3244.java:206)
	at net.minecraft.class_2535.method_10754(class_2535.java:233)
	at net.minecraft.class_3242.method_14357(class_3242.java:170)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:884)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$5723/1048288523.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1209815560 bytes (1153 MB) / 3433562112 bytes (3274 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		advancements-enlarger: Advancements Enlarger 0.2.2
		amecsapi: Amecs API 1.0.2+1.16-rc1
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		anvil_fix: AnvilFix 1.1.3+build.7-1.16
		appleskin: AppleSkin 1.0.11
		aquarius: Aquarius 1.0.1
		armorstandutils: Armor Stand Utils 1.0.1
		atmosfera: Atmosfera 1.2.2-1.16
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		autofish: Autofish 0.8.6
		autoswap: Autoswap 1.16-fabric0.13.1-1.0.1
		bambootweaks: Bamboo Tweaks unspecified
		beachslimes: Beach Slimes 2.1.0+mc1.16.1
		beenfo: Beenfo 1.16-fabric0.13.1-1.1
		better_wandering_trader: Better Wandering Trader 1.4.0
		better_wither_skeletons: Better Wither Skeletons 1.1.0
		betterthanmending: BetterThanMending 1.1.1
		blockmeter: Block Meter 1.16-fabric0.13.1-1.4.3
		blue_endless_jankson: jankson 1.1.2
		bucket-hat: Bucket Hat 1.0.2
		campanion: Campanion 1.1.13+build.35
		canvas: Canvas Renderer 1.0.867
		cardinal-components-base: Cardinal Components API (base) 2.4.1
		cardinal-components-chunk: Cardinal Components API (chunks) 2.4.1
		cardinal-components-entity: Cardinal Components API (entities) 2.4.1
		cardinal-components-item: Cardinal Components API (items) 2.4.0
		chainmail: Chainmail 0.3.0
		chunkactivator: Chunk Activator 2.1.0+mc1.16.1
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		connected_block_textures: Connected Block Textures 0.1.0+1.16
		controlling: Controlling For Fabric 1.1.2
		cotton: Cotton 1.0.5
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.5
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		couplings: Couplings 1.3.1
		craftingpad: Crafting Pad 1.16-fabric0.13.1-1.0.5
		creativebuttonmover: Creative Button Mover 0.2.5
		crowmap: Crowmap 1.0.1
		dark-loading-screen: Dark Loading Screen 1.3.2
		dataloader: Data Loader 2.1.0+mc1.16.1
		dontdropit: Don't Drop It! 1.2.2+1.16
		durabilityviewer: Giselbaers Durability Viewer 1.16-fabric0.13.1-1.7.2
		dynamicfps: Dynamic FPS 1.1.4
		dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
		earthtojavamobs: Earth2Java 1.0.1+1.16.1
		easierenchanting: Easier Enchanting 1.2.0
		ecotones: Ecotones 0.4.4
		elytra_swap: Elytra Swap 2.1.0-1.16.1
		enchantedtooltips: Enchanted ToolTips 1.3.1-1.16
		enderhopper: Ender Hopper 0.1.0
		expandedstorage: ExpandedStorage 5.3.16
		fabric: Fabric API 0.16.0+build.384-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474cb0
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-diagonal-panes: Fabric Diagonal Panes 0.3.0
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		fastfurnace: FastFurnace 2.2
		fatxporbs: Fat Experience Orbs 0.0.7
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fermion-orientation: Fermion Orientation 1.0.180-snapshot
		fermion-varia: Fermion Varia 2.1.191
		fishelp: Fishelp 1.0.2
		flight_display: Critical Flight Display 1.1.2
		fmagnet: Fabric Magnet 1.14-1.0.0
		forgivingenchantingtable: Forgiving Enchanting Table 2.1
		frex: FREX 3.2.132
		gamemodeoverhaul: GamemodeOverhaul 1.16.1-1.0.1.8
		gbfabrictools: GBfabrictools 1.2.2+1.16
		glassdoor: Glass Doors 1.4.4-1.16
		glassential: Glassential 1.16.1-1.1.4
		godown: Go Down 0.2.0+1.16.1
		grindenchantments: Grind Enchantments 1.1.1+1.16.1
		harvest: Harvest 1.2.12
		horsestatsvanilla: Horse Stats Vanilla 2.0.1
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		illuminations: Illuminations 1.0.1.1
		infinityfix: Infinity Fix 1.1.0
		inmis: Inmis 1.2.0-1.16.1
		inventorysorter: Inventory Sorter 1.7.0-1.16
		jankson: Jankson 3.0.0+j1.2.0
		joml-mod: JOML Mod 1.4.20
		json-model-extensions: JSON Model Extensions 1.11.116
		jumploader: Jumploader 2.0.0
		jumpoverfences: JumpOverFences 1.16-0.0.3
		justmap-unlimited: Just Map Unlimited 1.1.96
		kyrptconfig: Kytpt Config 1.0.4-1.16
		lakeside: Lakeside 1.0.2+1.16.1
		lambdynlights: LambDynamicLights 1.2.2+1.16.1
		leadvillagers: Lead Villagers 2.1.0+mc1.16.1
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		leafmealone: Leaf Me Alone 2.1
		libblockattributes: LibBlockAttributes 0.7.0
		libblockattributes_core: LibBlockAttributes (Core) 0.7.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.7.0
		libblockattributes_items: LibBlockAttributes (Items) 0.7.0
		libcd: LibCapableData 2.5.0+1.16.1
		libgamerule: LibGamerule ${version}
		libgui: LibGui 2.2.0+1.16.1
		libstructure: Libstructure 1.3
		lightoverlay: Light Overlay 5.4.1
		lithium: Lithium 0.5.1
		magna: Magna 1.1.3-1.16.1
		minecraft: Minecraft 1.16.1
		minime_paperdoll: Player Mini-Me (Paper Doll) 1.0.4
		missingbits: Missing Bits v1.16.1 Fabric b2
		modmenu: Mod Menu 1.14.5+build.30
		moenchantments: Mo'Enchantments 1.12.4-beta2
		mutuality: Mutuality 1.0.0
		nbtcrafting: NBT Crafting 2.0.0-beta.1+mc1.16.1
		ninjaphenix-container-lib: NinjaPhenix's Container Library 1.1.5
		nogizmo: No Debug Gizmo 1.1
		noncorrelatedextras: NonCorrelatedExtras 0.3.2
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		parchment: Parchment 1.0.2+1.15.2
		pathsuggestion: Path Suggestion 0.3.0
		phosphor: Phosphor 0.6.0+build.7
		pigpoop: Pig Poop 1.1.3
		plantinajar: Plant In A Jar 1.3.0+1.16.1
		playerabilitylib: Pal 1.2.0
		polymorph: Polymorph 0.0.2-1.16.1
		rainbucket: Rain Bucket 1.0.0
		randomblockplacement: RandomBlockPlacement 1.16-fabric0.13.1-1.1.1
		rare-ice: Rare Ice 0.2.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.3.2
		resourceloader: Fabric Resource Loader 1.1.0
		right-click-clear: Right Click Clear 2.0.2
		riverredux: River Redux 0.1.4
		roughlyenoughitems: Roughly Enough Items 4.10.3
		rpgstats: RPGStats 2.1.0+1.16.1
		scale: scale 0.0.0
		sheepconsistency: Sheep Consistency 1.0.2
		sign_editor: Better Signs & Frames mc-1.16.1-0.6.1
		silky_spawners: Silky Spawners 2.0.0+build.1-1.16
		sleepvote: SleepVote ${version}
		slotlink: slotlink 0.3.6+minecraft-1.16.1
		smokeextender: Smoke Extender 1.4.0
		smoothbedrock: Smooth Bedrock (Fabric) 1.2.3
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		snowy_leaves: Snowy Leaves 1.16.1-1.3.1
		soaring-clouds: Soaring Clouds 1.1.0-1.16
		special-circumstances: Special Circumstances 1.6.191
		speedtrading: Speed Trading 1.0.1+1.16
		spinnery: Spinnery 3.1.14
		spruceui: SpruceUI 1.5.8
		stackablepotions: Stackable Potions 1.0.0
		staffofbuilding: Staff of Building 1.2.0-1.16
		staticdata: Static Data 1.1.2
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		terraform: Terraform 2.1.7+build.31
		tinytweaks: TinyTweaks 1.0.11
		trapexpansion: Trap Expansion 1.3.2
		trash-it: Trash It 1.0.1-1.16.1
		trees-do-not-float: Trees Do Not Float 1.10.90
		tridentfixer: Repairable Tridents 1.0.0
		universalcomponents: Universal Components 0.7.2+1.16-pre2
		vanilla-hammers: Vanilla Hammers 2.0.1-1.16.1
		vanilladeathchest: VanillaDeathChest 1.16.1-1.11.0.4-fabric
		vanillaexcavators: Vanilla Excavators 1.1.0
		villagerhats: Villager Hats fabric-1.16-rc1-1.0.0
		waila: Hwyla 1.9.22
		winged: Winged Mod 1.16-1.2
		winwonders: Window Wonders 0.1.2
		woodcutter: Woodcutter 1.2-1.16.1
		wrenchable: Wrenchable 1.0.0+1.16.1
	Player Count: 1 / 8; [class_3222['FoxyLight'/216, l='ServerLevel[New World]', x=-130.50, y=66.00, z=130.50]]
	Data Packs: vanilla (incompatible), fabric/fmagnet, fabric/chunkactivator, fabric/noncorrelatedextras, fabric/villagerhats, fabric/repurposed_structures, fabric/enderhopper, fabric/trapexpansion, fabric/woodcutter, fabric/vanillaexcavators, fabric/ecotones, fabric/bambootweaks, fabric/cotton-commons, fabric/winged, fabric/harvest, fabric/inmis, fabric/aquarius, fabric/silky_spawners, fabric/craftingpad, fabric/staffofbuilding, fabric/glassential, fabric/rpgstats, fabric/forgivingenchantingtable, fabric/lambdynlights, fabric/iamverysmart, fabric/fabric-tool-attribute-api-v1, fabric/rare-ice, fabric/expandedstorage, fabric/earthtojavamobs, fabric/trash-it, fabric/libcd, fabric/vanilla-hammers, fabric/plantinajar, fabric/campanion, fabric/glassdoor, fabric/beachslimes, fabric/slotlink, fabric/better_wither_skeletons, Resource Loader pack, file/aof-strawberry (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by GabrielOlvH** [comment]
Try removing/updating Illuminations, it happened as well to me and friends on our server

**Comment by FoxyLight** [comment]
Awesome! Thanks so much. Tried updating Illuminations first and that didn't work, but removing did. Thanks again!

**Comment by Pyrofab** [comment]
Version 1.0.3 of Illuminations should fix this by the way.

**Comment by FoxyLight** [comment]
Cool thanks. It seemed like a nice mod. I'll give that version a try.
